:::caution Handling failures
The last point above translates to: the command service **does not throw exceptions**. It [returns](#result) an instance of `Result<TState>.Error` instead. It is your responsibility to handle the error.
:::
